export const GET_NFT_BY_USER_PENDING = 'app/Account/GET_NFT_BY_USER_PENDING';
export const GET_NFT_BY_USER_SUCCESS = 'app/Account/GET_NFT_BY_USER_SUCCESS';
export const GET_NFT_BY_USER_ERROR = 'app/Account/GET_NFT_BY_USER_ERROR';

export const UPDATE_USER_BACKGROUND_PENDING = 'app/Account/UPDATE_USER_BACKGROUND_PENDING';
export const UPDATE_USER_BACKGROUND_SUCCESS = 'app/Account/UPDATE_USER_BACKGROUND_SUCCESS';
export const UPDATE_USER_BACKGROUND_ERROR = 'app/Account/UPDATE_USER_BACKGROUND_ERROR';

export const GET_TRANSACTION_BY_USER_PENDING = 'app/Account/GET_TRANSACTION_BY_USER_PENDING';
export const GET_TRANSACTION_BY_USER_SUCCESS = 'app/Account/GET_TRANSACTION_BY_USER_SUCCESS';
export const GET_TRANSACTION_BY_USER_ERROR = 'app/Account/GET_TRANSACTION_BY_USER_ERROR';
