export const GET_USER_BY_ADMIN_PENDING = 'app/Admin/GET_USER_BY_ADMIN_PENDING';
export const GET_USER_BY_ADMIN_SUCCESS = 'app/Admin/GET_USER_BY_ADMIN_SUCCESS';
export const GET_USER_BY_ADMIN_ERROR = 'app/Admin/GET_USER_BY_ADMIN_ERROR';
export const SET_TAB = 'app/Admin/SET_TAB';

export const UPDATE_ROLE_USER_PENDING = 'app/Admin/UPDATE_ROLE_USER_PENDING';
export const UPDATE_ROLE_USER_SUCCESS = 'app/Admin/UPDATE_ROLE_USER_SUCCESS';
export const UPDATE_ROLE_USER_ERROR = 'app/Admin/UPDATE_ROLE_USER_ERROR';

export const GET_NFT_BY_ADMIN_PENDING = 'app/Admin/GET_NFT_BY_ADMIN_PENDING';
export const GET_NFT_BY_ADMIN_SUCCESS = 'app/Admin/GET_NFT_BY_ADMIN_SUCCESS';
export const GET_NFT_BY_ADMIN_ERROR = 'app/Admin/GET_NFT_BY_ADMIN_ERROR';

export const UPDATE_NFT_TRENDING_PENDING = 'app/Admin/UPDATE_NFT_TRENDING_PENDING';
export const UPDATE_NFT_TRENDING_SUCCESS = 'app/Admin/UPDATE_NFT_TRENDING_SUCCESS';
export const UPDATE_NFT_TRENDING_ERROR = 'app/Admin/UPDATE_NFT_TRENDING_ERROR';