export const GET_NFT_INFO_PENDING = 'app/Nft/GET_NFT_INFO_PENDING';
export const GET_NFT_INFO_SUCCESS = 'app/Nft/GET_NFT_INFO_SUCCESS';
export const GET_NFT_INFO_ERROR = 'app/Nft/GET_NFT_INFO_SUCCESS';

export const SYNC_NFT_MARKET_PENDING = 'app/Nft/SYNC_NFT_MARKET_PENDING';
export const SYNC_NFT_MARKET_SUCCESS = 'app/Nft/SYNC_NFT_MARKET_SUCCESS';
export const SYNC_NFT_MARKET_ERROR = 'app/Nft/SYNC_NFT_MARKET_ERROR';