export const GET_NFT_INFO_PENDING = 'app/Nft/GET_NFT_INFO_PENDING';
export const GET_NFT_INFO_SUCCESS = 'app/Nft/GET_NFT_INFO_SUCCESS';
export const GET_NFT_INFO_ERROR = 'app/Nft/GET_NFT_INFO_SUCCESS';

export const SYNC_NFT_MARKET_PENDING = 'app/Nft/SYNC_NFT_MARKET_PENDING';
export const SYNC_NFT_MARKET_SUCCESS = 'app/Nft/SYNC_NFT_MARKET_SUCCESS';
export const SYNC_NFT_MARKET_ERROR = 'app/Nft/SYNC_NFT_MARKET_ERROR';

export const BUY_NFT_BY_USER_PENDING = 'app/Nft/BUY_NFT_BY_USER_PENDING';
export const BUY_NFT_BY_USER_SUCCESS = 'app/Nft/BUY_NFT_BY_USER_SUCCESS';
export const BUY_NFT_BY_USER_ERROR = 'app/Nft/BUY_NFT_BY_USER_ERROR';
export const SET_LOADING_NFT = 'app/Nft/SET_LOADING';